package com.hastane.entity;

// Generated May 21, 2014 12:11:11 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Brans generated by hbm2java
 */
@Entity
@Table(name = "brans", catalog = "hastaneadmin")
public class Brans implements java.io.Serializable {

	private Integer bransId;
	private String bransAdi;
	private Set<Doktor> doktors = new HashSet<Doktor>(0);

	public Brans() {
	}

	public Brans(String bransAdi) {
		this.bransAdi = bransAdi;
	}

	public Brans(String bransAdi, Set<Doktor> doktors) {
		this.bransAdi = bransAdi;
		this.doktors = doktors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bransId", unique = true, nullable = false)
	public Integer getBransId() {
		return this.bransId;
	}

	public void setBransId(Integer bransId) {
		this.bransId = bransId;
	}

	@Column(name = "bransAdi", nullable = false)
	public String getBransAdi() {
		return this.bransAdi;
	}

	public void setBransAdi(String bransAdi) {
		this.bransAdi = bransAdi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brans")
	public Set<Doktor> getDoktors() {
		return this.doktors;
	}

	public void setDoktors(Set<Doktor> doktors) {
		this.doktors = doktors;
	}

}
