package com.hastane.entity;

// Generated May 21, 2014 12:11:11 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Doktor generated by hbm2java
 */
@Entity
@Table(name = "doktor", catalog = "hastaneadmin")
public class Doktor implements java.io.Serializable {

	private Integer doktorId;
	private Klinik klinik;
	private Brans brans;
	private String adi;
	private String soyadi;
	private Set<Randevu> randevus = new HashSet<Randevu>(0);

	public Doktor() {
	}

	public Doktor(Klinik klinik, Brans brans, String adi, String soyadi) {
		this.klinik = klinik;
		this.brans = brans;
		this.adi = adi;
		this.soyadi = soyadi;
	}

	public Doktor(Klinik klinik, Brans brans, String adi, String soyadi,
			Set<Randevu> randevus) {
		this.klinik = klinik;
		this.brans = brans;
		this.adi = adi;
		this.soyadi = soyadi;
		this.randevus = randevus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "doktorId", unique = true, nullable = false)
	public Integer getDoktorId() {
		return this.doktorId;
	}

	public void setDoktorId(Integer doktorId) {
		this.doktorId = doktorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "klinikId", nullable = false)
	public Klinik getKlinik() {
		return this.klinik;
	}

	public void setKlinik(Klinik klinik) {
		this.klinik = klinik;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bransId", nullable = false)
	public Brans getBrans() {
		return this.brans;
	}

	public void setBrans(Brans brans) {
		this.brans = brans;
	}

	@Column(name = "adi", nullable = false, length = 50)
	public String getAdi() {
		return this.adi;
	}

	public void setAdi(String adi) {
		this.adi = adi;
	}

	@Column(name = "soyadi", nullable = false, length = 50)
	public String getSoyadi() {
		return this.soyadi;
	}

	public void setSoyadi(String soyadi) {
		this.soyadi = soyadi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doktor")
	public Set<Randevu> getRandevus() {
		return this.randevus;
	}

	public void setRandevus(Set<Randevu> randevus) {
		this.randevus = randevus;
	}

}
