package com.hastane.entity;

// Generated May 21, 2014 12:11:11 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ilce generated by hbm2java
 */
@Entity
@Table(name = "ilce", catalog = "hastaneadmin")
public class Ilce implements java.io.Serializable {

	private Integer ilceId;
	private Il il;
	private String adi;

	public Ilce() {
	}

	public Ilce(Il il, String adi) {
		this.il = il;
		this.adi = adi;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ilceId", unique = true, nullable = false)
	public Integer getIlceId() {
		return this.ilceId;
	}

	public void setIlceId(Integer ilceId) {
		this.ilceId = ilceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sehirId", nullable = false)
	public Il getIl() {
		return this.il;
	}

	public void setIl(Il il) {
		this.il = il;
	}

	@Column(name = "adi", nullable = false, length = 25)
	public String getAdi() {
		return this.adi;
	}

	public void setAdi(String adi) {
		this.adi = adi;
	}

}
