package com.hastane.entity;

// Generated May 21, 2014 12:11:11 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Klinik generated by hbm2java
 */
@Entity
@Table(name = "klinik", catalog = "hastaneadmin")
public class Klinik implements java.io.Serializable {

	private Integer klinikId;
	private String klinkAdi;
	private Set<Doktor> doktors = new HashSet<Doktor>(0);

	public Klinik() {
	}

	public Klinik(String klinkAdi) {
		this.klinkAdi = klinkAdi;
	}

	public Klinik(String klinkAdi, Set<Doktor> doktors) {
		this.klinkAdi = klinkAdi;
		this.doktors = doktors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "klinikId", unique = true, nullable = false)
	public Integer getKlinikId() {
		return this.klinikId;
	}

	public void setKlinikId(Integer klinikId) {
		this.klinikId = klinikId;
	}

	@Column(name = "klinkAdi", nullable = false)
	public String getKlinkAdi() {
		return this.klinkAdi;
	}

	public void setKlinkAdi(String klinkAdi) {
		this.klinkAdi = klinkAdi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "klinik")
	public Set<Doktor> getDoktors() {
		return this.doktors;
	}

	public void setDoktors(Set<Doktor> doktors) {
		this.doktors = doktors;
	}

}
