package com.hastane.entity;

// Generated May 21, 2014 12:11:11 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Randevu generated by hbm2java
 */
@Entity
@Table(name = "randevu", catalog = "hastaneadmin")
public class Randevu implements java.io.Serializable {

	private Integer randevuId;
	private Doktor doktor;
	private Hasta hasta;
	private Date tarih;
	private int saatId;

	public Randevu() {
	}

	public Randevu(Doktor doktor, Hasta hasta, Date tarih, int saatId) {
		this.doktor = doktor;
		this.hasta = hasta;
		this.tarih = tarih;
		this.saatId = saatId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "randevuId", unique = true, nullable = false)
	public Integer getRandevuId() {
		return this.randevuId;
	}

	public void setRandevuId(Integer randevuId) {
		this.randevuId = randevuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doktorId", nullable = false)
	public Doktor getDoktor() {
		return this.doktor;
	}

	public void setDoktor(Doktor doktor) {
		this.doktor = doktor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hastaId", nullable = false)
	public Hasta getHasta() {
		return this.hasta;
	}

	public void setHasta(Hasta hasta) {
		this.hasta = hasta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tarih", nullable = false, length = 19)
	public Date getTarih() {
		return this.tarih;
	}

	public void setTarih(Date tarih) {
		this.tarih = tarih;
	}

	@Column(name = "saatId", nullable = false)
	public int getSaatId() {
		return this.saatId;
	}

	public void setSaatId(int saatId) {
		this.saatId = saatId;
	}

}
